# Generated by Django 4.2.16 on 2025-04-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_alter_transaction_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('buy', 'خرید'), ('sell', 'فروش')], default='buy', max_length=4),
        ),
    ]
