# Generated by Django 4.2.16 on 2025-05-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0005_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
